minimum_pre_commit_version: '2.9.3'

repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.21.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.3
    hooks:
      - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-test-repo-mod
      - id: go-build-repo-mod
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: mdtoc
        name: Markdown Table of Contents
        language: system
        entry: bash -euxc 'mdtocw() { if command -v mdtoc >/dev/null; then command mdtoc "$@"; else go run sigs.k8s.io/mdtoc@latest "$@"; fi; }; mdtocw --inplace "$@"' _
        files: ^README.md$
      - id: assertiface
        name: Validate Interface Assertions
        language: system
        entry: ./scripts/validate_types.sh
        files: (?<!_test)\.go$
        exclude: ^flag\.go$
