name: Validate

on:
  pull_request:
  push:
    branches:
      - main

env:
  GO111MODULE: on

jobs:
  DetermineVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: jdx/mise-action@v3
        with:
          install: false
        env:
          MISE_TRUSTED_CONFIG_PATHS: ${{ github.workspace }}
      - id: go-version-matrix
        run: |
          go_version="$(awk '/^go/{print $2}' go.mod)"
          echo "go_version=${go_version}.x" >> "$GITHUB_OUTPUT"

          matrix_versions="$(git ls-remote --tags https://github.com/golang/go |
              awk -F/ '$3 ~ /^go([0-9]+(\.[0-9]+)$)/{gsub(/^go/, "", $3); print $3}' |
              sort -V |
              sed -ne "/^$go_version$/,$ p" |
              jq -cMnR '[inputs | select(length>0)] | map(. + ".x")')"
          echo "matrix=${matrix_versions}" >> "$GITHUB_OUTPUT"

          golangci_version="$(mise ls 'github:golangci/golangci-lint' --current --json | jq -r '.[0].version')"
          echo "golangci_version=v${golangci_version}" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.go-version-matrix.outputs.matrix }}
      go_version: ${{ steps.go-version-matrix.outputs.go_version }}
      golangci_version: ${{ steps.go-version-matrix.outputs.golangci_version }}

  Pre-Commit:
    needs: DetermineVersion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - name: Setup go
        run: curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.3/install-go.pl | perl - ${{ needs.DetermineVersion.outputs.go_version }} $HOME
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ needs.DetermineVersion.outputs.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-mod
      - name: Setup mdtoc
        run: go install sigs.k8s.io/mdtoc@v1.1.0
      - uses: j178/prek-action@v3.0.0
        env:
          PREK_SKIP: golangci-lint,go-build,go-unit-tests

  GolangCI-Lint:
    needs: DetermineVersion
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        run: curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.3/install-go.pl | perl - ${{ needs.DetermineVersion.outputs.go_version }} $HOME
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ needs.DetermineVersion.outputs.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-mod
      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ needs.DetermineVersion.outputs.golangci_version }}

  Vet:
    needs: DetermineVersion
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        run: curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.3/install-go.pl | perl - ${{ needs.DetermineVersion.outputs.go_version }} $HOME
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ needs.DetermineVersion.outputs.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-mod
      - name: Run vet
        run: go vet

  Test:
    needs: DetermineVersion
    strategy:
      fail-fast: false
      matrix:
        go: ${{ fromJson(needs.DetermineVersion.outputs.matrix) }}
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        exclude:
          - os: macOS-latest
            go: 1.16.x
          - os: macOS-latest
            go: 1.17.x
          - os: macOS-latest
            go: 1.18.x
          - os: macOS-latest
            go: 1.19.x
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Go ${{ matrix.go }} Tests
    steps:
      - name: Setup go
        shell: bash
        run: curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.3/install-go.pl | perl - ${{ matrix.go }} $HOME
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-mod
      - name: Run tests
        shell: bash
        run: go test -v -cover -race

  Test-386:
    needs: DetermineVersion
    runs-on: ubuntu-latest
    name: linux/386 Go ${{ needs.DetermineVersion.outputs.go_version }} Tests
    env:
      GOARCH: "386"
      CGO_ENABLED: "0"
    steps:
      - name: Setup go
        run: curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.3/install-go.pl | perl - ${{ needs.DetermineVersion.outputs.go_version }} $HOME
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~/AppData/Local/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ needs.DetermineVersion.outputs.go_version }}-386-${{ hashFiles('**/go.sum') }}
          restore-keys: go-mod
      - name: Run tests
        run: go test -v -cover ./...
